---
# defaults for ivansible.ndm_openvpn

ndm_ovpn_servers: []
#  - name: default                # server name
#    active: true                 # optional flag
#    host: myserver.com           # server host or address
#    port: 1194                   # server port
#    proto: udp                   # tcp or udp
#    tun_mtu: 0                   # optional
#    proxy: ~                     # optional, eg. socks5://address:port
#    client_cert: '--- BEGIN...'  # client certificate as text
#    client_key: '--- BEGIN...'   # client key as text
#    server_cert: '--- BEGIN...'  # server certificate as text
#    ca_cert: '--- BEGIN...'      # CA certificate as text

## Settings below this line must be synchronized between openvpn roles

ndm_ovpn_tls13: false
ndm_ovpn_cipher: "AES-{{ ndm_ovpn_tls13 |bool |ternary(256,128) }}-GCM"
ndm_ovpn_hmac_alg: SHA256
ndm_ovpn_reneg_sec: ~  # cipher renegotiantion interval (default: 1 hour)
...
