---
namespace: ivansible
name: ndms
version: 1.0.0

description: Ansible collection for Keenetic NDMS

authors:
  - Ivan Andreev <ivandeex@gmail.com>

tags:
  - keenetic
  - ndms
  - network
  - firewall
  - vpn
  - openvpn
  - wireguard

# https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification
# namespace.name: version_range
dependencies: {}

repository: https://github.com/ivansible/ndms
documentation: https://github.com/ivansible/ndms
homepage: https://github.com/ivansible/ndms
issues: https://github.com/ivansible/ndms/issues

readme: README.md
license: MIT

build_ignore:
  - '*.pyc'
  - '*.tar'
...
