---
- name: configure ndm firewall
  ansible.builtin.import_tasks: firewall.yml
  when: ndm_firewall |d({})
  tags:
    - ndm_firewall_acl
    - ndm_firewall_all

- name: configure ndm forwarding
  ansible.builtin.import_tasks: forwarding.yml
  when: ndm_forwarding |d([])
  tags:
    - ndm_forwarding
    - ndm_firewall_fwd
    - ndm_firewall_all
...
