---
- name: configure wireguard for peer '{{ name }}'
  restconf_config2:
    path: /interface/{{ iface }}
    content: "{{ lookup('template', 'config.json.j2') |to_json }}"
    ## ansible treats templated string as a yaml map,
    ## replaces double by single quotes and fails.
    ## as a workaround, convert template result to json.
  tags: skip_ansible_lint
  register: wg_config_result

- name: configure one-time wireguard settings for peer '{{ name }}'
  restconf_config2:
    path: /interface/{{ iface }}
    content: "{{ lookup('template', 'onetime.json.j2') |to_json }}"
  tags: skip_ansible_lint
  when: wg_config_result is changed

- name: save new configuration for peer '{{ name }}'
  restconf_config2:
    path: /system/configuration
    content: '{"save": true}'
  tags: skip_ansible_lint
  when: wg_config_result is changed
...
